### ISSUE TITLE
Weather4Lox Website - Auto color scheme

### ISSUE THREAD

**Issue by mr-manuel** [mschlenstedt/LoxBerry-Plugin-Weather4Lox#112]
Add an option for auto color scheme for the theme which displays the same light/dark scheme as the client device has.

Example:

```css
<style>
      html, body {
        background: #000; color: #fff;
      }
      @media (prefers-color-scheme: light) {
        html, body {
          background: #fff; color: #000;
        }
      }
</style>
```
